## NumPy  Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
type(myarray)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(2,5)

array([[0.54684753, 0.66169379, 0.15193438, 0.81076204, 0.62516453],
       [0.98959853, 0.43325512, 0.40232234, 0.89537411, 0.32286156]])

In [15]:
np.random.randn(10)

array([-0.22304223,  0.45531673,  0.39744451, -0.10557012, -0.06658523,
       -1.58779858, -0.20814993,  0.56342013,  0.60919065,  0.37592599])

In [16]:
np.random.randint(0,101,size=(2,5))

array([[71, 48, 18, 44, 43],
       [75, 67, 57, 35, 92]])

In [17]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [18]:
arr = np.arange(25)

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
rand_arr = np.random.randint(0,101,10)

In [30]:
print(rand_arr)
print(rand_arr.max())
print(rand_arr.argmax())
print("---")
print(rand_arr.min())
print(rand_arr.argmin())
print(rand_arr.dtype)
print(rand_arr.shape)
rand_arr = rand_arr.reshape(2,5)
print(rand_arr)

[82 86 74 74 87 99 23  2 21 52]
99
5
---
2
7
int64
(10,)
[[82 86 74 74 87]
 [99 23  2 21 52]]
