## NumPy Indexing and Selections

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
print(arr[8])
print(arr[0:5])
print(arr[:-1])

8
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [6]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
slice_of_arr = arr[0:5]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[0 1 2 3 4]
[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [9]:
arr_copy = arr.copy()
arr_copy[:] = 100
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99  5  6  7  8  9 10]


In [14]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)
print(arr_2d.shape)
print(arr_2d[2])
print(arr_2d[0,2])
print(arr_2d[:2,1:])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3, 3)
[35 40 45]
15
[[10 15]
 [25 30]]


In [18]:
arr = np.arange(1,11)
print(arr)
print(arr > 4)
bool_arr = arr>4
print(arr[bool_arr])
print(arr[arr>4])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
